/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv ./worker-configuration.d.ts` (hash: 1413889952b3fe49b4d16d734060affa)
interface __BaseEnv_CloudflareEnv {
	LEADS_BUCKET: R2Bucket;
	ASSETS: Fetcher;
	TURNSTILE_SECRET: string;
	PLUNK_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/_worker.js/index");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TURNSTILE_SECRET" | "PLUNK_API_KEY">> {}
}
