/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ./worker-configuration.d.ts` (hash: 720d70d762d3b54ef23daae9611705e4)
interface __BaseEnv_Env {
	LEADS_BUCKET: R2Bucket;
	ASSETS: Fetcher;
	TURNSTILE_SECRET: string;
	PLUNK_API_KEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TURNSTILE_SECRET" | "PLUNK_API_KEY">> {}
}
