/// <reference types="astro/client" />
/// <reference types="@cloudflare/workers-types" />

/**
 * The Cloudflare Worker runtime environment.
 *
 * `Env` is generated by `pnpm cf-typegen` from wrangler.jsonc.
 * Keep worker-configuration.d.ts committed and checked in CI so bindings and
 * required secrets cannot drift away from the deploy config.
 *
 * Z360_TOKEN is intentionally optional and therefore cannot be generated from
 * Wrangler's required-secrets list. This declaration only augments the
 * generated Cloudflare environment; all required bindings remain generated.
 */
declare namespace Cloudflare {
  interface Env {
    /** Optional Z360 CRM token. When present (and enabled), leads are pushed to Z360. */
    Z360_TOKEN?: string;
  }
}
