/// <reference types="astro/client" />
/// <reference types="@cloudflare/workers-types" />

/**
 * The Cloudflare Worker runtime environment.
 *
 * `CloudflareEnv` is generated by `pnpm cf-typegen` from wrangler.jsonc.
 * Keep worker-configuration.d.ts committed and checked in CI so bindings and
 * required secrets cannot drift away from the deploy config.
 *
 * Optional per-site secrets can be added here when they are intentionally not
 * required for every deploy. Access runtime env in server code via
 * `context.locals.runtime.env`.
 */
interface Env extends CloudflareEnv {
  /** Optional Z360 CRM token. When present (and enabled), leads are pushed to Z360. */
  Z360_TOKEN?: string;
}

type Runtime = import("@astrojs/cloudflare").Runtime<Env>;

declare namespace App {
  interface Locals extends Runtime {}
}
